# config/services.yaml
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Import des services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # Configuration spécifique
    App\EventSubscriber\PanierSubscriber:
        tags: ['kernel.event_subscriber']
    
    # Configuration explicite pour Doctrine
    Doctrine\ORM\EntityManagerInterface: '@doctrine.orm.default_entity_manager'